### ISSUE TITLE
如果出现No such file or directory: 'strencode2.js'  怎么处理？

### ISSUE THREAD

**Issue by alexbbbb** [scriptcoder1/91pron_python#3]
如果出现No such file or directory: 'strencode2.js'  怎么处理？

**Comment by scriptcoder1** [comment]
那你肯定是打开的项目根目录，你用vs code直接打开demo文件夹就可以了

**Comment by alexbbbb** [comment]
我在vscode中直接git 项目，然后打卡了demo，F5，根据提示安装了模块，模块没问题后就是这个错误
怎么解决呢？
